---
- hosts: webserver
  become: True
  tasks:
   - name: Install apache
     yum:
      name: "apache"
      state: "present"
   - name: start apache
     service:
       name: apache
       state: started
       enabled: True
...
